/**
 * Plain-English framing per check, for anyone reading a report who doesn't
 * know what a canonical tag or JSON-LD @id is. Technical findings still
 * carry their exact message/url/detail — this is the "why should I care"
 * layer on top, not a replacement for it.
 */
export interface CheckExplanation {
  title: string;
  whyItMatters: string;
}

export const CHECK_EXPLANATIONS: Record<string, CheckExplanation> = {
  fetch: {
    title: "Broken pages",
    whyItMatters:
      "These pages return an error instead of loading. They're invisible to search engines re-checking them and to anyone who lands on one — from a search result, a shared link, or an old bookmark.",
  },
  canonical: {
    title: "Duplicate-content signals",
    whyItMatters:
      "Search engines use a page's \"canonical\" tag to decide which version of it is the real one to rank. When it's missing, wrong, or copy-pasted across many pages, search engines can pick the wrong page as authoritative — or drop the real ones out of search results entirely. This is the exact bug class that caused this site's pages to disappear from Google.",
  },
  redirects: {
    title: "Redirect health (www / https)",
    whyItMatters:
      "Visitors and search engines reach a site through slightly different URLs — with or without \"www\", http or https. Each should land on the correct page in one hop. Extra hops slow the page down and occasionally break outright, and can dilute the ranking value a link is passing along.",
  },
  "structured-data": {
    title: "Structured data (rich results) accuracy",
    whyItMatters:
      "This is the machine-readable summary search engines use for rich results — FAQ dropdowns, star ratings, business info in search listings. When the same block is copy-pasted across unrelated pages, search engines lose confidence in what's real, which can suppress rich results.",
  },
  "sitemap-reliability": {
    title: "Sitemap reliability",
    whyItMatters:
      "The sitemap is the map handed to search engines listing every page that exists. If it's flaky — sometimes complete, sometimes missing entries — new content gets discovered slower and existing pages can fall out of the regular crawl rotation.",
  },
  favicon: {
    title: "Brand presentation",
    whyItMatters:
      "The small icon shown in browser tabs, bookmarks, and some search results. A broken one looks unprofessional, and its breakage often points at a deploy step that's quietly failing.",
  },
  "meta-tags": {
    title: "Page titles & descriptions",
    whyItMatters:
      "The title and description are what shows up as the blue link and the snippet underneath it in search results — they're the actual ad copy for a page. Missing ones get auto-generated by the search engine (usually worse), and the same title/description copy-pasted across many pages means search engines can't tell those pages apart either.",
  },
  images: {
    title: "Image accessibility",
    whyItMatters:
      "Alt text is what screen readers announce and what search engines use to understand an image (including for image search results). Missing it entirely — not the same as an intentionally empty alt on a decorative image — is a real accessibility gap.",
  },
  "robots-meta": {
    title: "Accidental noindex",
    whyItMatters:
      "A page can be told not to index it two different ways. Often intentional — but a page that's listed in the sitemap while also being marked noindex is a contradiction worth a second look; it usually means one of the two was set by accident.",
  },
  links: {
    title: "Broken internal links",
    whyItMatters:
      "Links a real visitor would actually click, not just what's listed in the sitemap. A broken internal link is a dead end for both visitors and the search engine crawl path that follows links to discover pages.",
  },
  "page-changes": {
    title: "Changes since last scan",
    whyItMatters:
      "Most of these are informational, not errors — a title or canonical changing might be a deliberate edit. This is visibility: knowing something changed, so an unexpected one (a page suddenly erroring, or getting marked noindex) gets caught the same day instead of weeks later.",
  },
};

export function explainCheck(check: string): CheckExplanation {
  return (
    CHECK_EXPLANATIONS[check] ?? {
      title: check,
      whyItMatters: "",
    }
  );
}
